### ISSUE TITLE
能不把密码放在配置里吗？想放在一个 .env 文件里，方便提交到 git 上

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#8]
cli 生成的配置文件

```yml
port: 8086
adapters:
  icqq:
    bots:
      - uin: xxx
        password: -
        platform: 1
        master: xxx
        data_dir: data
self_url: localhost
data_dir: data
plugin_dir: plugins
plugins:
  watcher: /Users/linonetwo/Desktop/repo/qq-bot
log_level: info
services: {}
delay:
  prompt: 60000
logConfig:
  appenders:
    consoleOut:
      type: console
    saveFile:
      type: file
      filename: /Users/linonetwo/Desktop/repo/qq-bot/logs.log
  categories:
    default:
      appenders:
        - consoleOut
        - saveFile
      level: info
```

能不把密码放在这里吗？想放在一个 。env 文件里
