### ISSUE TITLE
其它插件是做什么的？

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#9]
```
plugins:
  config: null # 指定启用配置管理插件
  daemon: null # 指定启用守护进程插件
  help: null # 指定启用帮助插件
  login: null # 指定启用命令行登录插件
  plugin: null # 指定启用插件管理插件
  systemInfo: null # 指定启用系统信息查看插件
  watcher: plugins # 指定启用文件监听插件
  repeater: null # 指定启用复读机插件 
```

没有文档
